humanoid_arm:
  ros__parameters:
    motors:
      motor_14:
        reverse: false
        offset: -1.2240207949334987
      motor_15:
        reverse: false
        offset: -2.6417066643375597
      motor_16:
        reverse: false
        offset: -1.5625511800600111
      motor_17:
        reverse: false
        offset: 2.968636319755687
      motor_18:
        reverse: false
        offset: -0.6513665920559404
      motor_19:
        reverse: false
        offset: 2.668743075724044
      motor_20:
        reverse: false
        offset: -0.7156020375486516
      motor_21:
        reverse: false
        offset: -0.8661239023599302
      motor_22:
        reverse: false
        offset: -2.383230901578829
      motor_23:
        reverse: false
        offset: 0.8784916224622581
