humanoid_arm:
  ros__parameters:
    motors:
      motor_14:
        reverse: false
        offset: -1.0384091195993361
      motor_15:
        reverse: false
        offset: -2.309887445158047
      motor_16:
        reverse: false
        offset: 0.591157846131429
      motor_17:
        reverse: false
        offset: 2.824250378095951
      motor_18:
        reverse: false
        offset: -0.056086172557068756
      motor_19:
        reverse: false
        offset: 2.8934712611492905
      motor_20:
        reverse: false
        offset: -0.6286445016353843
      motor_21:
        reverse: false
        offset: -1.1407064633914599
      motor_22:
        reverse: false
        offset: -2.5325064069999508
      motor_23:
        reverse: false
        offset: 0.7975741359012906
