humanoid_arm:
  ros__parameters:
    motors:
      motor_14:
        reverse: false
        offset: -1.205804773077357
      motor_15:
        reverse: false
        offset: -2.554557380825807
      motor_16:
        reverse: false
        offset: -1.7881422296784433
      motor_17:
        reverse: false
        offset: 3.0189700643581845
      motor_18:
        reverse: false
        offset: -0.07372695161775362
      motor_19:
        reverse: false
        offset: 2.727801336057641
      motor_20:
        reverse: false
        offset: -0.6622003313703827
      motor_21:
        reverse: false
        offset: -0.9178957539510705
      motor_22:
        reverse: false
        offset: -2.3432515272945595
      motor_23:
        reverse: false
        offset: -0.15550730237190688
