humanoid_arm:
  ros__parameters:
    motors:
      motor_14:
        reverse: false
        offset: -1.2844212884564958
      motor_15:
        reverse: false
        offset: -2.5753619952615057
      motor_16:
        reverse: false
        offset: 0.36221121353949703
      motor_17:
        reverse: false
        offset: 3.0723717705364537
      motor_18:
        reverse: false
        offset: -0.09012137128828135
      motor_19:
        reverse: false
        offset: 2.8136083863799946
      motor_20:
        reverse: false
        offset: -0.6323835798058556
      motor_21:
        reverse: false
        offset: -1.0997683511147618
      motor_22:
        reverse: false
        offset: -2.5347115043825363
      motor_23:
        reverse: false
        offset: 0.8041894280490474
