humanoid_base:
  ros__parameters:
    head: "205D32834D31"
    motors:
      motor_1:
        device: "2064378F5948"
        reverse: true
        offset: -0.017
      motor_2:
        device: "2064378F5948"
        reverse: false
        offset: -0.273
      motor_3:
        device: "205732834D31"
        reverse: false
        offset: -0.179
      motor_4:
        device: "205732834D31"
        reverse: false
        offset: 0.0
      motor_5:
        device: "205732834D31"
        reverse: true
        offset: 0.138
      motor_6:
        device: "205732834D31"
        reverse: true
        offset: 1.5475
      motor_7:
        device: "205732834D31"
        reverse: false
        offset: 1.9135
      motor_8:
        device: "2064378F5948"
        reverse: false
        offset: -0.048
      motor_9:
        device: "206F32844D31"
        reverse: false
        offset: -0.435
      motor_10:
        device: "206F32844D31"
        reverse: true
        offset: 0.348
      motor_11:
        device: "206F32844D31"
        reverse: false
        offset: 0.3157
      motor_12:
        device: "206F32844D31"
        reverse: true
        offset: 0.2095
      motor_13:
        device: "206F32844D31"
        reverse: false
        offset: 1.0245
